{{ if not .Values.node.certificate.autoGenerate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certificate-name" .}}
type: Opaque
data:
  cert.pem: {{ .Values.node.certificate.contents | b64enc }}
{{ end }}