apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "icon-node.podSecurityPolicyName" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "icon-node.podSecurityPolicyName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts