{{ if not .Values.node.certificate.autoGenerate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icon-node.certificate-password" .}}
type: Opaque
data:
  password: {{ .Values.node.certificate.password | b64enc }}
{{ end }}