apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpcService" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.node.ports.rpc }}
      name: json-rpc
  selector:
{{ include "selectorLabels" . | indent 4 }}
  type: LoadBalancer
