apiVersion: v1
kind: Service
metadata:
  name: {{ include "p2pService" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.node.network.p2p.port }}
      name: p2p
  selector:
{{ include "selectorLabels" . | indent 4 }}
  type: {{ .Values.service.rpc.type | default "NodePort" }}